name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v --disable-warnings

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test  # ⚠️ Запускается ТОЛЬКО если job test прошёл успешно

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 104.164.54.139
          port: 33
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/TelegramServerBot
            git pull origin main
            python -m pip install --upgrade pip
            pip install -r requirements.txt --no-cache-dir
            systemctl restart tgbot.service
            echo "Deployment completed"
